In [3]:
import random

import numpy as np
print(np)

<module 'numpy' from 'C:\\Users\\moura\\miniconda3\\Lib\\site-packages\\numpy\\__init__.py'>


3. Create a null vector of size 10S

In [21]:
a= np.empty(8)
print(a)

[4.67296746e-307 1.69121096e-306 1.86921279e-306 1.89146896e-307
 7.56571288e-307 3.11525958e-307 1.24610723e-306 1.29061142e-306]


 4.How to find the memory size of any array

In [25]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.size*a.itemsize)

72


5. How to get the documentation of the numpy add function from the command line?

In [29]:
hint: np.info
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python'` not found.

6. Create a null vector of size 10 but the fifth value which is 1

In [5]:
a=np.zeros((8,5))
a[5]=1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


7.Create a vector with values ranging from 10 to 49

In [31]:
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


ESERCIZIO 1
Write a function that takes a 1d numpy array and computes its reverse vector
(last element becomes the first).
oss:parti dall'ultimo e poi vai indietro fino alla fine di -1 ogni volta

In [36]:
a=np.arange(10)
print(a[-1::-1])

[9 8 7 6 5 4 3 2 1 0]



9. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
a=np.arange(9).reshape(3,3)
print(a)

NameError: name 'np' is not defined


11. Create a 3x3 identity matrix 

In [46]:
a=np.eye(2,2)
print(a)

[[1. 0.]
 [0. 1.]]


12. Create a 3x3x3 array with random values 

In [28]:
a=np.random.uniform(2,3,[3,3,3])
print(a)

[[[2.1551592  2.34587206 2.96762703]
  [2.97424341 2.92942882 2.43413924]
  [2.93821268 2.77596574 2.59980845]]

 [[2.61354474 2.94574721 2.52279096]
  [2.35809125 2.75485014 2.78988861]
  [2.24474409 2.52968561 2.29928018]]

 [[2.20430235 2.87011217 2.02001483]
  [2.14061676 2.22927156 2.20413764]
  [2.7194502  2.89275072 2.08406601]]]


13. Create a 10x10 array with random values and find the minimum and maximum values 

In [33]:
a=np.random.randint(2,4,[10,10])
print(np.max(a))

3


14. Create a random vector of size 30 and find the mean value

In [16]:
a=np.random.randint(0,1,[30])
print(np.mean(a))

0.0


15. Create a 2d array with 1 on the border and 0 inside

In [67]:
a=np.ones([4,4])
a[1:3,1:3] = 0
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [86]:
a=np.ones([4,4])
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [102]:
a=np.diag([1,2,3,4],-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [145]:
a=np.ones([8,8])
n=8
a[::2,::2]=0
a[1::2,1::2]=0   
        
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [174]:
a=np.ones([6,7,8])
a[2,0:1,0:1]=3
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


22. Normalize a 5x5 random matrix

In [185]:
a=np.random.randint(2,4,(5,5))
a_norm=((a-np.mean(a))/(np.std(a)))
print(a_norm)


[[-0.88640526 -0.88640526  1.12815215  1.12815215  1.12815215]
 [ 1.12815215 -0.88640526  1.12815215 -0.88640526  1.12815215]
 [-0.88640526 -0.88640526  1.12815215 -0.88640526 -0.88640526]
 [-0.88640526  1.12815215 -0.88640526  1.12815215  1.12815215]
 [-0.88640526 -0.88640526 -0.88640526  1.12815215 -0.88640526]]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [196]:
a=np.ones((5,3))
b=np.arange(6).reshape(3,2)
c=np.matmul(a,b)#prodotto matriciale
print(c)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 1]
 [2 3]
 [4 5]]
[[6. 9.]
 [6. 9.]
 [6. 9.]
 [6. 9.]
 [6. 9.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [210]:
a=np.arange(10)
a[3:9]*=-1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


29. How to round away from zero a float array ?

In [19]:
a=np.random.uniform(-6,10,[10])
a=np.floor(a)#rende positivo il vettore
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


36. Extract the integer part of a random array of positive numbers using 4 different methods 

In [258]:
a=np.array([1,2.3,3.3])
condition=a%1==0
t=np.extract(condition,a)
print(t)

[1.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [275]:
a=np.zeros((5,5))
a+=np.arange(5).reshape(5,1)#con resceipe la fai diventare una colonna
print(a)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [5]:
a=np.linspace(0.1,1.0,10)
print(a)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


ESERCIZIO 2
Given the following square array, compute the product of the elements on its
diagonal. [[1 3 8] [-1 3 0] [-3 9 2]]


40. Create a random vector of size 10 and sort it

In [13]:
a=np.random.randint(0,10,10)
a.sort()
print(a)

[1 2 2 2 3 3 8 8 9 9]


42. Consider two random array A and B, check if they are equal

In [20]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(np.array_equal(a,b))

True


45. Create random vector of size 10 and replace the maximum value by 0 

In [43]:
a=np.random.randint(0,10,10)
print(np.max(a))
a=np.where(a==np.max(a),0,a)
print(a)

9
[6 0 6 3 4 5 7 0 0 6]


 • Given two arrays a and b, compute how many time an item of a is higher than the
 corresponding element of b.

In [55]:
a=np.array([[3,2,7], [1,2,3]])
b=np.array([[2,2,4] ,[0,1,4]])
print(np.greater(a,b))


[[ True False  True]
 [ True  True False]]


In [52]:
a=np.array([[1, 3, 8], [-1, 3, 0], [-3, 9, 2]])
#modo 1
print(a[0:1,0:1]+a[1:2,1:2]+a[2:3,2:3])
#modo 2
print(a.diagonal().sum())


[[6]]
6
